paths:
  uploads: uploads
  static: ''
  collections: ''
  data: ''
collections_config:
  pages:
    path: src/content/pages
    output: true
    url: '/[full_slug]/'
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - visual
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  recipes:
    path: src/content/recipes
    output: true
    url: '/[full_slug]/'
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _enabled_editors:
      - visual
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_inputs:
  related_recipe:
    type: url
timezone: Etc/UTC
